[tool.poetry]
name = "xcoll"
version = "0.1.0"
description = "Xsuite collimation package"
repository = "https://github.com/xsuite/xcoll"
authors = [
           "Frederik F. Van der Veken <frederik@cern.ch>",
           "Despina Demetriadou <despina.demetriadou@cern.ch>",
           "Andrey Abramov <andrey.abramov@cern.ch>",
           "Giovanni Iadorala <giovanni.iadorala@cern.ch>"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11" # The upper bound is required by scipy
numpy = ">=1.22.3"
pandas = ">=1.4.2"
scipy = ">=1.8.0"
xobjects = ">=0.1.12"
xdeps = ">=0.0.5"
xpart = ">=0.6.1"
xtrack = ">=0.12.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyter = "^1.0.0"
ipykernel = "^6.13.0"

[build-system]
# Needed for pip install -e (BTW: need pip version 22)
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"
